# Apple iOS System Update

DOMAIN,mesu.apple.com,DIRECT
DOMAIN,gdmf.apple.com,DIRECT
DOMAIN,gg.apple.com,DIRECT
DOMAIN,gs.apple.com,DIRECT
DOMAIN,appldnld.apple.com,DIRECT
DOMAIN,updates.cdn-apple.com,DIRECT
DOMAIN,updates-http.cdn-apple.com,DIRECT
DOMAIN,xp.apple.com,DIRECT